name: Build and deploy Node.js app to Azure Web App - Chakravyuh

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".husky"
      - ".github/**"
      - "**/*.csv"
      - apps/backend/.env*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: create env file
        run: |
          touch apps/backend/.env
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> apps/backend/.env
          echo "DEEPGRAM_API_KEY=${{ secrets.DEEPGRAM_API_KEY }}" >> apps/backend/.env
          echo "DEEPGRAM_VOICE_ID=${{ secrets.DEEPGRAM_VOICE_ID }}" >> apps/backend/.env
          echo "NODE_ENV=development" >> apps/backend/.env
          
      - name: yarn install, build, and test
        run: |
          cd apps/backend
          yarn
          yarn dev

      - name: Zip all files for upload between jobs
        run: cd apps/backend && zip -r next.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: apps/backend/next.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip apps/backend/next.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2D8E03F54A104892BE642945E4A7CCA8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_74051CD16489455B842900771684C24D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_38EEB679C50D463F8E0FC587F6702F89 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Chakravyuh'
          slot-name: 'Production'
          package: apps/backend
